[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
; Auto-detect XIAO ESP32-C6 by Espressif USB VID:PID
board_build.arduino.hwids =
    0x303A 0x1001
lib_deps =
    knolleary/PubSubClient @ ^2.8
    https://github.com/Love4yzp/Seeed-mmWave-library
    https://github.com/ESP32Async/AsyncTCP
    https://github.com/ESP32Async/ESPAsyncWebServer
    tzapu/WiFiManager @ ^2.0
